// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescription.Models;

#nullable disable

namespace Prescription.Migrations
{
    [DbContext(typeof(PrescriptionContext))]
    partial class PrescriptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Prescription.Models.PrescriptionModel", b =>
                {
                    b.Property<int>("PrescriptionModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionModelId");

                    b.ToTable("PrescriptionModel");

                    b.HasData(
                        new
                        {
                            PrescriptionModelId = 1,
                            Cost = 12.5,
                            FillStatus = "Pending",
                            MedicationName = "Amoxicillin",
                            RequestTime = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionModelId = 2,
                            Cost = 8.75,
                            FillStatus = "Filled",
                            MedicationName = "Ibuprofen",
                            RequestTime = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionModelId = 3,
                            Cost = 20.0,
                            FillStatus = "Denied",
                            MedicationName = "Metformin",
                            RequestTime = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
